version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: avis_postgres
    environment:
      POSTGRES_USER: avis_user
      POSTGRES_PASSWORD: avis_password
      POSTGRES_DB: avis_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
