/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentUpdate
 */
export interface AppointmentUpdate {
    /**
     * 
     * @type {string}
     * @memberof AppointmentUpdate
     */
    slotId?: string;
}

/**
 * Check if a given object implements the AppointmentUpdate interface.
 */
export function instanceOfAppointmentUpdate(value: object): value is AppointmentUpdate {
    return true;
}

export function AppointmentUpdateFromJSON(json: any): AppointmentUpdate {
    return AppointmentUpdateFromJSONTyped(json, false);
}

export function AppointmentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'slotId': json['slot_id'] == null ? undefined : json['slot_id'],
    };
}

export function AppointmentUpdateToJSON(json: any): AppointmentUpdate {
    return AppointmentUpdateToJSONTyped(json, false);
}

export function AppointmentUpdateToJSONTyped(value?: AppointmentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slot_id': value['slotId'],
    };
}

