/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentCreate
 */
export interface AppointmentCreate {
    /**
     * 
     * @type {string}
     * @memberof AppointmentCreate
     */
    donorId: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentCreate
     */
    centerId: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentCreate
     */
    slotId: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentCreate
     */
    notes?: string;
}

/**
 * Check if a given object implements the AppointmentCreate interface.
 */
export function instanceOfAppointmentCreate(value: object): value is AppointmentCreate {
    if (!('donorId' in value) || value['donorId'] === undefined) return false;
    if (!('centerId' in value) || value['centerId'] === undefined) return false;
    if (!('slotId' in value) || value['slotId'] === undefined) return false;
    return true;
}

export function AppointmentCreateFromJSON(json: any): AppointmentCreate {
    return AppointmentCreateFromJSONTyped(json, false);
}

export function AppointmentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'donorId': json['donor_id'],
        'centerId': json['center_id'],
        'slotId': json['slot_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function AppointmentCreateToJSON(json: any): AppointmentCreate {
    return AppointmentCreateToJSONTyped(json, false);
}

export function AppointmentCreateToJSONTyped(value?: AppointmentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'donor_id': value['donorId'],
        'center_id': value['centerId'],
        'slot_id': value['slotId'],
        'notes': value['notes'],
    };
}

