/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Center
 */
export interface Center {
    /**
     * 
     * @type {string}
     * @memberof Center
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Center
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Center
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof Center
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof Center
     */
    lng?: number;
    /**
     * 
     * @type {string}
     * @memberof Center
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Center
     */
    openingHours?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Center
     */
    donationTypes?: Array<string>;
}

/**
 * Check if a given object implements the Center interface.
 */
export function instanceOfCenter(value: object): value is Center {
    return true;
}

export function CenterFromJSON(json: any): Center {
    return CenterFromJSONTyped(json, false);
}

export function CenterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Center {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lng': json['lng'] == null ? undefined : json['lng'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'openingHours': json['opening_hours'] == null ? undefined : json['opening_hours'],
        'donationTypes': json['donation_types'] == null ? undefined : json['donation_types'],
    };
}

export function CenterToJSON(json: any): Center {
    return CenterToJSONTyped(json, false);
}

export function CenterToJSONTyped(value?: Center | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'lat': value['lat'],
        'lng': value['lng'],
        'phone': value['phone'],
        'opening_hours': value['openingHours'],
        'donation_types': value['donationTypes'],
    };
}

