/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonationRecord
 */
export interface DonationRecord {
    /**
     * 
     * @type {string}
     * @memberof DonationRecord
     */
    donationId?: string;
    /**
     * 
     * @type {Date}
     * @memberof DonationRecord
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof DonationRecord
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof DonationRecord
     */
    centerId?: string;
}

/**
 * Check if a given object implements the DonationRecord interface.
 */
export function instanceOfDonationRecord(value: object): value is DonationRecord {
    return true;
}

export function DonationRecordFromJSON(json: any): DonationRecord {
    return DonationRecordFromJSONTyped(json, false);
}

export function DonationRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'donationId': json['donation_id'] == null ? undefined : json['donation_id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'type': json['type'] == null ? undefined : json['type'],
        'centerId': json['center_id'] == null ? undefined : json['center_id'],
    };
}

export function DonationRecordToJSON(json: any): DonationRecord {
    return DonationRecordToJSONTyped(json, false);
}

export function DonationRecordToJSONTyped(value?: DonationRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'donation_id': value['donationId'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'type': value['type'],
        'center_id': value['centerId'],
    };
}

