/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonorUpdate
 */
export interface DonorUpdate {
    /**
     * 
     * @type {string}
     * @memberof DonorUpdate
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof DonorUpdate
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DonorUpdate
     */
    gdprConsent?: boolean;
}

/**
 * Check if a given object implements the DonorUpdate interface.
 */
export function instanceOfDonorUpdate(value: object): value is DonorUpdate {
    return true;
}

export function DonorUpdateFromJSON(json: any): DonorUpdate {
    return DonorUpdateFromJSONTyped(json, false);
}

export function DonorUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonorUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'gdprConsent': json['gdpr_consent'] == null ? undefined : json['gdpr_consent'],
    };
}

export function DonorUpdateToJSON(json: any): DonorUpdate {
    return DonorUpdateToJSONTyped(json, false);
}

export function DonorUpdateToJSONTyped(value?: DonorUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'email': value['email'],
        'gdpr_consent': value['gdprConsent'],
    };
}

