/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationsSubscribePostRequest
 */
export interface NotificationsSubscribePostRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationsSubscribePostRequest
     */
    deviceToken?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationsSubscribePostRequest
     */
    platform?: NotificationsSubscribePostRequestPlatformEnum;
    /**
     * 
     * @type {object}
     * @memberof NotificationsSubscribePostRequest
     */
    preferences?: object;
}


/**
 * @export
 */
export const NotificationsSubscribePostRequestPlatformEnum = {
    Ios: 'ios',
    Android: 'android'
} as const;
export type NotificationsSubscribePostRequestPlatformEnum = typeof NotificationsSubscribePostRequestPlatformEnum[keyof typeof NotificationsSubscribePostRequestPlatformEnum];


/**
 * Check if a given object implements the NotificationsSubscribePostRequest interface.
 */
export function instanceOfNotificationsSubscribePostRequest(value: object): value is NotificationsSubscribePostRequest {
    return true;
}

export function NotificationsSubscribePostRequestFromJSON(json: any): NotificationsSubscribePostRequest {
    return NotificationsSubscribePostRequestFromJSONTyped(json, false);
}

export function NotificationsSubscribePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsSubscribePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceToken': json['device_token'] == null ? undefined : json['device_token'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'preferences': json['preferences'] == null ? undefined : json['preferences'],
    };
}

export function NotificationsSubscribePostRequestToJSON(json: any): NotificationsSubscribePostRequest {
    return NotificationsSubscribePostRequestToJSONTyped(json, false);
}

export function NotificationsSubscribePostRequestToJSONTyped(value?: NotificationsSubscribePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_token': value['deviceToken'],
        'platform': value['platform'],
        'preferences': value['preferences'],
    };
}

