/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Slot
 */
export interface Slot {
    /**
     * 
     * @type {string}
     * @memberof Slot
     */
    slotId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Slot
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Slot
     */
    end?: Date;
    /**
     * 
     * @type {number}
     * @memberof Slot
     */
    available?: number;
}

/**
 * Check if a given object implements the Slot interface.
 */
export function instanceOfSlot(value: object): value is Slot {
    return true;
}

export function SlotFromJSON(json: any): Slot {
    return SlotFromJSONTyped(json, false);
}

export function SlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Slot {
    if (json == null) {
        return json;
    }
    return {
        
        'slotId': json['slot_id'] == null ? undefined : json['slot_id'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'available': json['available'] == null ? undefined : json['available'],
    };
}

export function SlotToJSON(json: any): Slot {
    return SlotToJSONTyped(json, false);
}

export function SlotToJSONTyped(value?: Slot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slot_id': value['slotId'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'available': value['available'],
    };
}

