/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestResult
 */
export interface TestResult {
    /**
     * 
     * @type {string}
     * @memberof TestResult
     */
    testId?: string;
    /**
     * 
     * @type {Date}
     * @memberof TestResult
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof TestResult
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof TestResult
     */
    fileUrl?: string;
}

/**
 * Check if a given object implements the TestResult interface.
 */
export function instanceOfTestResult(value: object): value is TestResult {
    return true;
}

export function TestResultFromJSON(json: any): TestResult {
    return TestResultFromJSONTyped(json, false);
}

export function TestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'testId': json['test_id'] == null ? undefined : json['test_id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'fileUrl': json['file_url'] == null ? undefined : json['file_url'],
    };
}

export function TestResultToJSON(json: any): TestResult {
    return TestResultToJSONTyped(json, false);
}

export function TestResultToJSONTyped(value?: TestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'test_id': value['testId'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'summary': value['summary'],
        'file_url': value['fileUrl'],
    };
}

