/* tslint:disable */
/* eslint-disable */
/**
 * AVIS Donazioni API
 * API per l\'app mobile AVIS (Italia) per la gestione delle donazioni di sangue. Lingua primaria: italiano (supporto inglese opzionalmente). Implementazione MVP ispirata al NHS Give Blood (booking, centri, storico donazioni, notifiche). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@avis.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NotificationsSubscribePostRequest,
} from '../models/index';
import {
    NotificationsSubscribePostRequestFromJSON,
    NotificationsSubscribePostRequestToJSON,
} from '../models/index';

export interface NotificationsSubscribePostOperationRequest {
    notificationsSubscribePostRequest: NotificationsSubscribePostRequest;
}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * Registra token per notifiche push
     */
    async notificationsSubscribePostRaw(requestParameters: NotificationsSubscribePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['notificationsSubscribePostRequest'] == null) {
            throw new runtime.RequiredError(
                'notificationsSubscribePostRequest',
                'Required parameter "notificationsSubscribePostRequest" was null or undefined when calling notificationsSubscribePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/subscribe`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationsSubscribePostRequestToJSON(requestParameters['notificationsSubscribePostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Registra token per notifiche push
     */
    async notificationsSubscribePost(requestParameters: NotificationsSubscribePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsSubscribePostRaw(requestParameters, initOverrides);
    }

}
